"""Retained-size policy shared by bounded Project read producers."""

PROJECT_LIST_MAX_PAGE_ITEMS = 25
PROJECT_PAPER_LIST_MAX_PAGE_ITEMS = 10
PROJECT_DESCRIPTION_JSON_BYTES = 512
PROJECT_TEXT_JSON_BYTES = 256
PROJECT_PAPER_LONG_TEXT_JSON_BYTES = 512
PROJECT_PAPER_LIST_VALUE_JSON_BYTES = 128
PROJECT_PAPER_KEYWORD_JSON_BYTES = 96
PROJECT_PAPER_MAX_AUTHORS = 6
PROJECT_PAPER_MAX_INSTITUTIONS = 4
PROJECT_PAPER_MAX_KEYWORDS = 8
PROJECT_PAPER_MAX_TAGS = 8

__all__ = [
    "PROJECT_DESCRIPTION_JSON_BYTES",
    "PROJECT_LIST_MAX_PAGE_ITEMS",
    "PROJECT_PAPER_KEYWORD_JSON_BYTES",
    "PROJECT_PAPER_LIST_MAX_PAGE_ITEMS",
    "PROJECT_PAPER_LIST_VALUE_JSON_BYTES",
    "PROJECT_PAPER_LONG_TEXT_JSON_BYTES",
    "PROJECT_PAPER_MAX_AUTHORS",
    "PROJECT_PAPER_MAX_INSTITUTIONS",
    "PROJECT_PAPER_MAX_KEYWORDS",
    "PROJECT_PAPER_MAX_TAGS",
    "PROJECT_TEXT_JSON_BYTES",
]
