"""Canonical Agent-facing tools for long-running Scholens research workspaces.

The catalog deliberately excludes internet paper discovery and generative product
features. It exposes the stored-knowledge, ingestion, organization, collaboration,
and annotation surface shared by the in-product Agent and external MCP clients.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import cast

from app.bootstrap.capabilities import ApplicationCapabilities
from app.bootstrap.workflows.citation import CitationWorkflow
from app.bootstrap.workflows.paper_ingestion import PaperIngestionWorkflow
from app.modules.jobs.application.contracts import JobListResponse, JobResponse
from app.modules.papers.application.contracts.documents import (
    CollectPublicPaperResponse,
    DocumentFileUrlResponse,
    DocumentResponse,
    LibraryPaperIngestionResponse,
    LibraryPaperListResponse,
    LibraryPaperResponse,
    LibrarySummaryResponse,
)
from app.modules.papers.application.contracts.tags import (
    LibraryTagAssignmentResponse,
    LibraryTagListResponse,
    LibraryTagResponse,
)
from app.modules.papers.application.upload_sessions import (
    PreparePaperUploadRequest,
    PreparePaperUploadResponse,
)
from app.modules.projects.application.contracts import (
    ProjectCollaboratorListResponse,
    ProjectInvitationListResponse,
    ProjectListResponse,
    ProjectPaperCollectedResponse,
    ProjectPaperListResponse,
    ProjectPapersAddedResponse,
)
from app.modules.research.application.contracts import ResearchItemResponse
from app.shared.application import ApplicationExecutor
from app.shared.domain import WorkspacePermission
from app.tooling import workspace_contracts as wc
from app.tooling.catalog import ToolCatalog, ToolProfile
from app.tooling.contracts import (
    ToolBehavior,
    ToolConfirmationPolicy,
    ToolDefinition,
    ToolExecutionKind,
    ToolHandler,
    WorkflowToolHandler,
)
from app.tooling.workspace_handlers import WorkspaceToolHandlers
from pydantic import BaseModel

CONVERSATION_TOOL_PROFILE = "conversation"
MCP_TOOL_PROFILE = "mcp"


def _description(*, use: str, avoid: str, result: str, next_step: str) -> str:
    """Build a consistent decision-oriented description without implementation detail."""
    return (
        f"Use when {use}. Do not use when {avoid}. Returns {result}. Next: {next_step}"
    )


def _tool(
    *,
    name: str,
    title: str,
    description: str,
    input_model: type[BaseModel],
    output_model: type[BaseModel],
    permission: WorkspacePermission,
    handler: Callable[..., object],
    execution: ToolExecutionKind = ToolExecutionKind.QUERY,
    destructive: bool = False,
    idempotent: bool | None = None,
    open_world: bool = False,
    confirmation: bool = False,
    persist_result: bool = True,
    subject: str | None = None,
) -> ToolDefinition[ApplicationCapabilities]:
    behavior = ToolBehavior(
        read_only=execution is ToolExecutionKind.QUERY,
        destructive=destructive,
        idempotent=(
            execution is ToolExecutionKind.QUERY if idempotent is None else idempotent
        ),
        open_world=open_world,
    )
    policy = (
        ToolConfirmationPolicy.REQUIRED if confirmation else ToolConfirmationPolicy.NONE
    )
    if execution is ToolExecutionKind.WORKFLOW:
        return ToolDefinition(
            name=name,
            title=title,
            description=description,
            input_model=input_model,
            output_model=output_model,
            execution=execution,
            required_permission=permission,
            behavior=behavior,
            confirmation_policy=policy,
            persist_result=persist_result,
            workflow_handler=cast(WorkflowToolHandler, handler),
            activity_subject_field=subject,
        )
    return ToolDefinition(
        name=name,
        title=title,
        description=description,
        input_model=input_model,
        output_model=output_model,
        execution=execution,
        required_permission=permission,
        behavior=behavior,
        confirmation_policy=policy,
        persist_result=persist_result,
        handler=cast(ToolHandler[ApplicationCapabilities], handler),
        activity_subject_field=subject,
    )


def build_workspace_tool_catalog(
    *,
    ingestion: PaperIngestionWorkflow,
    citations: CitationWorkflow,
    executor: ApplicationExecutor[ApplicationCapabilities] | None = None,
    web_base_url: str = "https://scholens.local",
    cursor_secret: str = "catalog-construction-only",
) -> ToolCatalog[ApplicationCapabilities]:
    handlers = WorkspaceToolHandlers(
        executor=cast(ApplicationExecutor[ApplicationCapabilities], executor),
        ingestion=ingestion,
        citations=citations,
        web_base_url=web_base_url,
        cursor_secret=cursor_secret,
    )
    read = WorkspacePermission.READ
    write = WorkspacePermission.WRITE
    manage = WorkspacePermission.MANAGE
    delete = WorkspacePermission.DELETE
    query = ToolExecutionKind.QUERY
    command = ToolExecutionKind.COMMAND
    workflow = ToolExecutionKind.WORKFLOW
    confirmed = wc.ConfirmationAwareAction

    definitions = [
        _tool(
            name="search_scholens_knowledge",
            title="Search Scholens knowledge",
            description=_description(
                use="you need facts or prior work already stored in Scholens",
                avoid="you need to discover papers on the internet",
                result="ranked paper, passage, annotation, comment, and output matches",
                next_step="open the relevant bounded resource before citing or changing it.",
            ),
            input_model=wc.SearchKnowledgeInput,
            output_model=wc.KnowledgeSearchOutput,
            permission=read,
            handler=handlers.search_knowledge,
            execution=query,
            subject="query",
        ),
        _tool(
            name="get_paper",
            title="Get paper metadata",
            description=_description(
                use="you know a Scholens document UUID and need canonical metadata",
                avoid="you need full text or internet discovery",
                result="the paper identity, metadata, processing state, and stable resource link",
                next_step="use get_paper_content or search_paper_content for evidence.",
            ),
            input_model=wc.DocumentInput,
            output_model=DocumentResponse,
            permission=read,
            handler=handlers.get_paper,
        ),
        _tool(
            name="get_paper_content",
            title="Read bounded paper text",
            description=_description(
                use="you need a bounded range of extracted text from a known paper",
                avoid="you only need metadata or do not know the document UUID",
                result="numbered lines, a content digest, and the next line cursor",
                next_step="continue with next_start_line or cite the returned line range.",
            ),
            input_model=wc.PaperContentInput,
            output_model=wc.PaperContentOutput,
            permission=read,
            handler=handlers.get_paper_content,
        ),
        _tool(
            name="search_paper_content",
            title="Search inside one paper",
            description=_description(
                use="you know the paper UUID and need locations matching text or a pattern",
                avoid="you need cross-paper search",
                result="bounded matching lines with source locators",
                next_step="read surrounding lines with get_paper_content before concluding.",
            ),
            input_model=wc.SearchPaperContentInput,
            output_model=wc.PaperContentSearchOutput,
            permission=read,
            handler=handlers.search_paper_content,
            subject="query",
        ),
        _tool(
            name="get_paper_citation",
            title="Read citation metadata",
            description=_description(
                use="you need stored bibliographic fields and their completeness",
                avoid="you want to contact external metadata providers",
                result="citation fields, missing required fields, and guidance",
                next_step="call resolve_paper_citation only when important fields are missing.",
            ),
            input_model=wc.PaperCitationInput,
            output_model=wc.PaperCitationReadOutput,
            permission=read,
            handler=handlers.get_paper_citation,
        ),
        _tool(
            name="resolve_paper_citation",
            title="Resolve missing citation metadata",
            description=_description(
                use="stored citation fields are incomplete and external resolution is justified",
                avoid="get_paper_citation reports complete metadata",
                result="resolved fields with provenance and a stable paper resource",
                next_step="persist the returned citation in the research document.",
            ),
            input_model=wc.ResolvePaperCitationInput,
            output_model=wc.ResolvedCitationOutput,
            permission=write,
            handler=handlers.resolve_paper_citation,
            execution=workflow,
            open_world=True,
        ),
        _tool(
            name="get_paper_download_url",
            title="Get temporary paper download URL",
            description=_description(
                use="an authorized client needs the original PDF bytes",
                avoid="you only need extracted text or metadata",
                result="a short-lived authenticated download URL and expiry",
                next_step="download promptly and never persist the temporary URL.",
            ),
            input_model=wc.DocumentInput,
            output_model=DocumentFileUrlResponse,
            permission=read,
            handler=handlers.get_paper_download_url,
        ),
        _tool(
            name="list_projects",
            title="List Projects",
            description=_description(
                use="you need to find an accessible Project or its immutable UUID",
                avoid="a repository already records the exact Project UUID",
                result="a cursor-paginated Project list",
                next_step="store the chosen project_id in AGENTS.md or README.",
            ),
            input_model=wc.ListProjectsInput,
            output_model=ProjectListResponse,
            permission=read,
            handler=handlers.list_projects,
        ),
        _tool(
            name="get_project",
            title="Get Project manifest",
            description=_description(
                use="you know a Project UUID and need its durable research binding",
                avoid="you are searching by title",
                result="Project metadata, capabilities, resource URI, web URL, and binding snippet",
                next_step="record the immutable UUID and scholens:// URI in the repository.",
            ),
            input_model=wc.ProjectInput,
            output_model=wc.ProjectToolResponse,
            permission=read,
            handler=handlers.get_project,
        ),
        _tool(
            name="create_project",
            title="Create Project",
            description=_description(
                use="a long-running research effort needs a new shared Scholens boundary",
                avoid="a matching Project already exists",
                result="the new Project manifest and repository-binding snippet",
                next_step="write the returned UUID and resource URI into the repository guidance.",
            ),
            input_model=wc.CreateProjectInput,
            output_model=wc.ProjectToolResponse,
            permission=write,
            handler=handlers.create_project,
            execution=command,
        ),
        _tool(
            name="update_project",
            title="Update Project",
            description=_description(
                use="the Project title or research description must change",
                avoid="you are trying to change ownership or members",
                result="the updated Project manifest",
                next_step="refresh repository prose if it quotes changed human-readable metadata.",
            ),
            input_model=wc.UpdateProjectInput,
            output_model=wc.ProjectToolResponse,
            permission=write,
            handler=handlers.update_project,
            execution=command,
            idempotent=True,
        ),
        _tool(
            name="delete_project",
            title="Delete Project",
            description=_description(
                use="the user explicitly wants to permanently remove the entire Project",
                avoid="the user only wants to leave, remove a paper, or archive local notes",
                result="first an impact preview, then a completion receipt after confirmation",
                next_step="present the preview and retry unchanged only after explicit approval.",
            ),
            input_model=wc.DeleteProjectInput,
            output_model=confirmed,
            permission=delete,
            handler=handlers.delete_project,
            execution=command,
            destructive=True,
            confirmation=True,
        ),
        _tool(
            name="list_project_papers",
            title="List Project papers",
            description=_description(
                use="you need the papers already associated with one Project",
                avoid="you need internet discovery or personal-Library-only papers",
                result="a filtered, cursor-paginated Project paper list",
                next_step="use returned document UUIDs with paper and annotation tools.",
            ),
            input_model=wc.ListProjectPapersInput,
            output_model=ProjectPaperListResponse,
            permission=read,
            handler=handlers.list_project_papers,
        ),
        _tool(
            name="add_papers_to_project",
            title="Add papers to Project",
            description=_description(
                use="known accessible Scholens papers should join a Project",
                avoid="the paper has not been ingested yet",
                result="counts of newly added and already-present papers",
                next_step="use list_project_papers to verify the Project manifest.",
            ),
            input_model=wc.AddPapersToProjectInput,
            output_model=ProjectPapersAddedResponse,
            permission=write,
            handler=handlers.add_papers_to_project,
            execution=command,
            idempotent=True,
        ),
        _tool(
            name="remove_paper_from_project",
            title="Remove paper from Project",
            description=_description(
                use="a paper association and its Project-scoped research context must be removed",
                avoid="you want to retain Project annotations or only remove a personal Library entry",
                result="first the exact annotation impact, then a completion receipt",
                next_step="present the preview and retry unchanged only after approval.",
            ),
            input_model=wc.ProjectPaperInput,
            output_model=confirmed,
            permission=delete,
            handler=handlers.remove_paper_from_project,
            execution=command,
            destructive=True,
            confirmation=True,
        ),
        _tool(
            name="list_paper_projects",
            title="List paper Projects",
            description=_description(
                use="you need every accessible Project containing a known paper",
                avoid="you only need the paper's personal Library status",
                result="a Project list",
                next_step="choose an explicit Project UUID for Project-scoped work.",
            ),
            input_model=wc.DocumentInput,
            output_model=ProjectListResponse,
            permission=read,
            handler=handlers.list_paper_projects,
        ),
        _tool(
            name="list_project_members",
            title="List Project members",
            description=_description(
                use="you need collaborator identities, roles, or permissions",
                avoid="you need pending invitations",
                result="visible Project collaborators and immutable user IDs",
                next_step="use those IDs for member or ownership changes.",
            ),
            input_model=wc.ProjectInput,
            output_model=ProjectCollaboratorListResponse,
            permission=read,
            handler=handlers.list_project_members,
        ),
        _tool(
            name="list_project_invitations",
            title="List Project invitations",
            description=_description(
                use="a Project manager needs pending invitation status",
                avoid="you need accepted members",
                result="pending invitations and their permissions",
                next_step="resend or revoke only the specific invitation UUID.",
            ),
            input_model=wc.ProjectInput,
            output_model=ProjectInvitationListResponse,
            permission=manage,
            handler=handlers.list_project_invitations,
        ),
        _tool(
            name="create_project_invitation",
            title="Invite Project collaborator",
            description=_description(
                use="the user explicitly wants to email Project access to a person",
                avoid="the person is already a member or email delivery is not intended",
                result="an impact preview, then invitation and delivery status",
                next_step="confirm before queueing, then inspect delivery status.",
            ),
            input_model=wc.CreateProjectInvitationInput,
            output_model=confirmed,
            permission=manage,
            handler=handlers.create_project_invitation,
            execution=workflow,
            open_world=True,
            confirmation=True,
        ),
        _tool(
            name="resend_project_invitation",
            title="Resend Project invitation",
            description=_description(
                use="a specific sent or failed invitation must be queued again",
                avoid="permissions or recipient must change",
                result="an impact preview, then refreshed invitation and delivery status",
                next_step="confirm before queueing and revoke/recreate if recipient details are wrong.",
            ),
            input_model=wc.InvitationInput,
            output_model=confirmed,
            permission=manage,
            handler=handlers.resend_project_invitation,
            execution=workflow,
            open_world=True,
            confirmation=True,
        ),
        _tool(
            name="revoke_project_invitation",
            title="Revoke Project invitation",
            description=_description(
                use="a pending invitation must stop granting future access",
                avoid="the invitee already accepted and is now a member",
                result="an impact preview, then a revocation receipt",
                next_step="confirm the exact invitation UUID before retrying.",
            ),
            input_model=wc.InvitationInput,
            output_model=confirmed,
            permission=manage,
            handler=handlers.revoke_project_invitation,
            execution=command,
            destructive=True,
            confirmation=True,
        ),
        _tool(
            name="accept_project_invitation",
            title="Accept Project invitation",
            description=_description(
                use="the current user wants to join using their own invitation token",
                avoid="the token belongs to someone else or the user has not approved joining",
                result="an impact preview, then the joined Project manifest",
                next_step="confirm, then bind the returned Project UUID where appropriate.",
            ),
            input_model=wc.AcceptProjectInvitationInput,
            output_model=confirmed,
            permission=manage,
            handler=handlers.accept_project_invitation,
            execution=command,
            confirmation=True,
        ),
        _tool(
            name="update_project_member",
            title="Update Project member",
            description=_description(
                use="an owner's collaborator permissions must change",
                avoid="ownership should transfer or the member should be removed",
                result="an impact preview, then the updated membership",
                next_step="confirm the complete replacement permission set.",
            ),
            input_model=wc.UpdateProjectMemberInput,
            output_model=confirmed,
            permission=manage,
            handler=handlers.update_project_member,
            execution=command,
            confirmation=True,
        ),
        _tool(
            name="remove_project_member",
            title="Remove Project member",
            description=_description(
                use="an owner explicitly wants to revoke a collaborator's Project access",
                avoid="the current user is leaving or ownership should transfer",
                result="an impact preview, then an access-removal receipt",
                next_step="confirm the immutable user ID before retrying.",
            ),
            input_model=wc.RemoveProjectMemberInput,
            output_model=confirmed,
            permission=manage,
            handler=handlers.remove_project_member,
            execution=command,
            destructive=True,
            confirmation=True,
        ),
        _tool(
            name="leave_project",
            title="Leave Project",
            description=_description(
                use="the current non-owner user explicitly wants to lose Project access",
                avoid="the owner has not transferred ownership",
                result="an impact preview, then a departure receipt",
                next_step="remove obsolete repository bindings after confirmation.",
            ),
            input_model=wc.LeaveProjectInput,
            output_model=confirmed,
            permission=manage,
            handler=handlers.leave_project,
            execution=command,
            destructive=True,
            confirmation=True,
        ),
        _tool(
            name="transfer_project_ownership",
            title="Transfer Project ownership",
            description=_description(
                use="the owner explicitly wants an existing collaborator to become owner",
                avoid="only collaborator permissions should change",
                result="an impact preview, then the resulting Project membership state",
                next_step="verify the new owner ID before confirmation.",
            ),
            input_model=wc.TransferProjectOwnershipInput,
            output_model=confirmed,
            permission=manage,
            handler=handlers.transfer_project_ownership,
            execution=command,
            confirmation=True,
        ),
        _tool(
            name="get_library_summary",
            title="Get Library summary",
            description=_description(
                use="you need counts and attention signals for the personal Library",
                avoid="you need individual paper records",
                result="paper, ingestion, attention, and output counts",
                next_step="list the relevant entity type for details.",
            ),
            input_model=wc.EmptyInput,
            output_model=LibrarySummaryResponse,
            permission=read,
            handler=handlers.get_library_summary,
        ),
        _tool(
            name="list_library_papers",
            title="List Library papers",
            description=_description(
                use="you need papers explicitly saved in the current user's Library",
                avoid="you need all Project-accessible papers or internet discovery",
                result="a filtered cursor-paginated Library list including active ingestions",
                next_step="use a document UUID for paper, Project, or tag operations.",
            ),
            input_model=wc.ListLibraryPapersInput,
            output_model=LibraryPaperListResponse,
            permission=read,
            handler=handlers.list_library_papers,
        ),
        _tool(
            name="get_library_paper",
            title="Get Library paper",
            description=_description(
                use="you need one personal Library entry, tags, status, and overrides",
                avoid="the paper is only accessible through a Project",
                result="the personal entry plus canonical document metadata",
                next_step="update only personal fields or use get_paper for canonical data.",
            ),
            input_model=wc.DocumentInput,
            output_model=LibraryPaperResponse,
            permission=read,
            handler=handlers.get_library_paper,
        ),
        _tool(
            name="update_library_paper",
            title="Update Library paper",
            description=_description(
                use="personal reading status or metadata overrides must change",
                avoid="canonical shared metadata should change",
                result="the updated personal Library entry",
                next_step="read the entry again if another actor may have changed it.",
            ),
            input_model=wc.UpdateLibraryPaperInput,
            output_model=LibraryPaperResponse,
            permission=write,
            handler=handlers.update_library_paper,
            execution=command,
            idempotent=True,
        ),
        _tool(
            name="remove_library_papers",
            title="Remove Library papers",
            description=_description(
                use="the user explicitly wants one or more personal Library entries removed",
                avoid="Project associations or shared documents should be deleted",
                result="an impact preview, then exact removed document UUIDs",
                next_step="confirm the full UUID set before retrying.",
            ),
            input_model=wc.RemoveLibraryPapersInput,
            output_model=confirmed,
            permission=delete,
            handler=handlers.remove_library_papers,
            execution=command,
            destructive=True,
            confirmation=True,
        ),
        _tool(
            name="collect_project_paper_to_library",
            title="Collect Project paper",
            description=_description(
                use="a Project-accessible paper should also be saved personally",
                avoid="the paper is already in the personal Library",
                result="the collected document UUID",
                next_step="use get_library_paper for personal status and tags.",
            ),
            input_model=wc.CollectProjectPaperInput,
            output_model=ProjectPaperCollectedResponse,
            permission=write,
            handler=handlers.collect_project_paper_to_library,
            execution=command,
            idempotent=True,
        ),
        _tool(
            name="share_library_paper",
            title="Share Library paper",
            description=_description(
                use="the user explicitly wants a public read/download link",
                avoid="access should remain limited to Scholens collaborators",
                result="an impact preview, then public token and web URL",
                next_step="confirm public exposure before retrying.",
            ),
            input_model=wc.SharedPaperInput,
            output_model=confirmed,
            permission=manage,
            handler=handlers.share_library_paper,
            execution=command,
            open_world=True,
            confirmation=True,
            persist_result=False,
        ),
        _tool(
            name="unshare_library_paper",
            title="Disable Library paper share",
            description=_description(
                use="an existing public link must stop working",
                avoid="a Project collaborator should be removed instead",
                result="an impact preview, then a privacy-change receipt",
                next_step="confirm that existing external links should break.",
            ),
            input_model=wc.SharedPaperInput,
            output_model=confirmed,
            permission=manage,
            handler=handlers.unshare_library_paper,
            execution=command,
            destructive=True,
            confirmation=True,
        ),
        _tool(
            name="collect_shared_paper",
            title="Collect shared paper",
            description=_description(
                use="the current user wants a publicly shared Scholens paper in their Library",
                avoid="the input is a general PDF URL",
                result="the personal Library entry identity and duplicate status",
                next_step="use get_library_paper or add_papers_to_project.",
            ),
            input_model=wc.CollectSharedPaperInput,
            output_model=CollectPublicPaperResponse,
            permission=write,
            handler=handlers.collect_shared_paper,
            execution=command,
            idempotent=True,
        ),
        _tool(
            name="list_library_tags",
            title="List Library tags",
            description=_description(
                use="you need the current user's personal tag UUIDs and names",
                avoid="you need Project-wide labels",
                result="the personal Library tag list",
                next_step="use tag UUIDs in list or replace-assignment operations.",
            ),
            input_model=wc.EmptyInput,
            output_model=LibraryTagListResponse,
            permission=read,
            handler=handlers.list_library_tags,
        ),
        _tool(
            name="create_library_tag",
            title="Create Library tag",
            description=_description(
                use="a new personal organization label is needed",
                avoid="an equivalent tag already exists",
                result="the created tag UUID and name",
                next_step="assign it with replace_library_paper_tags.",
            ),
            input_model=wc.CreateLibraryTagInput,
            output_model=LibraryTagResponse,
            permission=write,
            handler=handlers.create_library_tag,
            execution=command,
        ),
        _tool(
            name="update_library_tag",
            title="Rename Library tag",
            description=_description(
                use="a personal tag name must change",
                avoid="paper assignments should change",
                result="the renamed tag",
                next_step="continue using the same immutable tag UUID.",
            ),
            input_model=wc.UpdateLibraryTagInput,
            output_model=LibraryTagResponse,
            permission=write,
            handler=handlers.update_library_tag,
            execution=command,
            idempotent=True,
        ),
        _tool(
            name="delete_library_tag",
            title="Delete Library tag",
            description=_description(
                use="the user explicitly wants a personal tag removed everywhere",
                avoid="only selected paper assignments should change",
                result="an impact preview, then a deletion receipt",
                next_step="confirm that every assignment should be removed.",
            ),
            input_model=wc.DeleteLibraryTagInput,
            output_model=confirmed,
            permission=delete,
            handler=handlers.delete_library_tag,
            execution=command,
            destructive=True,
            confirmation=True,
        ),
        _tool(
            name="replace_library_paper_tags",
            title="Replace Library paper tags",
            description=_description(
                use="you know the complete desired tag set for selected Library papers",
                avoid="you intend to add tags without replacing unspecified ones",
                result="the number of updated papers and task status",
                next_step="list Library papers with tag filters to verify.",
            ),
            input_model=wc.ReplaceLibraryPaperTagsInput,
            output_model=LibraryTagAssignmentResponse,
            permission=write,
            handler=handlers.replace_library_paper_tags,
            execution=command,
            idempotent=True,
        ),
        _tool(
            name="ingest_paper",
            title="Ingest known paper",
            description=_description(
                use="you already know a DOI, arXiv ID, PDF URL, or prepared upload ID",
                avoid="you are searching the internet for relevant papers",
                result="a durable asynchronous ingestion identity and initial state",
                next_step="poll get_job and then use the returned document UUID.",
            ),
            input_model=wc.IngestPaperInput,
            output_model=LibraryPaperIngestionResponse,
            permission=write,
            handler=handlers.ingest_paper,
            execution=workflow,
            open_world=True,
        ),
        _tool(
            name="retry_paper_ingestion",
            title="Retry paper ingestion",
            description=_description(
                use="a specific failed ingestion job reports a retryable failure",
                avoid="the job is active, completed, or requires different source data",
                result="the restarted ingestion identity and state",
                next_step="poll get_job using the returned job identity.",
            ),
            input_model=wc.RetryPaperIngestionInput,
            output_model=LibraryPaperIngestionResponse,
            permission=write,
            handler=handlers.retry_paper_ingestion,
            execution=workflow,
            open_world=True,
        ),
        _tool(
            name="cancel_paper_ingestion",
            title="Cancel paper ingestion",
            description=_description(
                use="the user explicitly wants a pending or running ingestion stopped",
                avoid="the job is completed or merely slow",
                result="an impact preview, then a cancellation receipt",
                next_step="confirm the exact job UUID before retrying.",
            ),
            input_model=wc.CancelPaperIngestionInput,
            output_model=confirmed,
            permission=delete,
            handler=handlers.cancel_paper_ingestion,
            execution=workflow,
            destructive=True,
            confirmation=True,
        ),
        _tool(
            name="prepare_paper_upload",
            title="Prepare PDF upload",
            description=_description(
                use="a client can upload known PDF bytes directly to the returned URL",
                avoid="you only have a DOI, arXiv ID, or already reachable PDF URL",
                result="a one-file upload session, required headers, expiry, and upload_id",
                next_step="PUT the exact bytes, then call ingest_paper with source.kind=upload.",
            ),
            input_model=PreparePaperUploadRequest,
            output_model=PreparePaperUploadResponse,
            permission=write,
            handler=handlers.prepare_paper_upload,
            execution=command,
            open_world=True,
            persist_result=False,
        ),
        _tool(
            name="list_jobs",
            title="List jobs",
            description=_description(
                use="you need asynchronous ingestion or research operation status",
                avoid="you already know one job UUID",
                result="filtered active or historical jobs",
                next_step="use get_job for one exact status and actionable failure.",
            ),
            input_model=wc.ListJobsInput,
            output_model=JobListResponse,
            permission=read,
            handler=handlers.list_jobs,
        ),
        _tool(
            name="get_job",
            title="Get job",
            description=_description(
                use="you know a job UUID and need its exact progress or failure",
                avoid="you are searching across jobs",
                result="current status, progress code, result, and failure fields",
                next_step="retry only when the reported failure is retryable.",
            ),
            input_model=wc.JobInput,
            output_model=JobResponse,
            permission=read,
            handler=handlers.get_job,
        ),
        _tool(
            name="list_annotation_threads",
            title="List annotation threads",
            description=_description(
                use="you need visible discussions anchored to one paper",
                avoid="you need generated research outputs",
                result="bounded thread summaries and stable resource links",
                next_step="open one thread for complete comments before replying.",
            ),
            input_model=wc.ListAnnotationThreadsInput,
            output_model=wc.ThreadListOutput,
            permission=read,
            handler=handlers.list_annotation_threads,
        ),
        _tool(
            name="get_annotation_thread",
            title="Get annotation thread",
            description=_description(
                use="you know a thread UUID and need its quote, anchor, state, and comments",
                avoid="you are searching for a thread",
                result="the complete visible annotation thread",
                next_step="reply, update, or cite it using the immutable thread UUID.",
            ),
            input_model=wc.AnnotationThreadInput,
            output_model=ResearchItemResponse,
            permission=read,
            handler=handlers.get_annotation_thread,
        ),
        _tool(
            name="create_annotation_thread",
            title="Create annotation thread",
            description=_description(
                use="an exact stored-paper passage needs an anchored note or discussion",
                avoid="you cannot provide exact quote text and Reader position",
                result="the created thread and stable resource URI",
                next_step="use the URI or thread UUID in durable research notes.",
            ),
            input_model=wc.CreateAnnotationThreadInput,
            output_model=wc.ThreadActionOutput,
            permission=write,
            handler=handlers.create_annotation_thread,
            execution=command,
        ),
        _tool(
            name="update_annotation_thread",
            title="Update annotation thread",
            description=_description(
                use="the thread color or open/resolved status must change",
                avoid="quote text, audience, or comments should change",
                result="the updated thread",
                next_step="read it again when coordinating concurrent collaborators.",
            ),
            input_model=wc.UpdateAnnotationThreadInput,
            output_model=wc.ThreadActionOutput,
            permission=write,
            handler=handlers.update_annotation_thread,
            execution=command,
            idempotent=True,
        ),
        _tool(
            name="delete_annotation_thread",
            title="Delete annotation thread",
            description=_description(
                use="the creator explicitly wants a thread and its discussion removed",
                avoid="resolving the thread is sufficient",
                result="an impact preview, then a deletion receipt",
                next_step="confirm comment loss before retrying.",
            ),
            input_model=wc.DeleteAnnotationThreadInput,
            output_model=confirmed,
            permission=delete,
            handler=handlers.delete_annotation_thread,
            execution=command,
            destructive=True,
            confirmation=True,
        ),
        _tool(
            name="create_annotation_comment",
            title="Reply to annotation thread",
            description=_description(
                use="you need to add substantive discussion to an existing thread",
                avoid="you need a new paper anchor",
                result="the created comment and parent thread resource",
                next_step="use get_annotation_thread to see the full discussion.",
            ),
            input_model=wc.CreateAnnotationCommentInput,
            output_model=wc.CommentActionOutput,
            permission=write,
            handler=handlers.create_annotation_comment,
            execution=command,
        ),
        _tool(
            name="update_annotation_comment",
            title="Update annotation comment",
            description=_description(
                use="the current actor's existing comment text must be replaced",
                avoid="you need to reply or edit another person's comment",
                result="the updated comment and parent thread resource",
                next_step="read the thread to verify discussion context.",
            ),
            input_model=wc.UpdateAnnotationCommentInput,
            output_model=wc.CommentActionOutput,
            permission=write,
            handler=handlers.update_annotation_comment,
            execution=command,
            idempotent=True,
        ),
        _tool(
            name="delete_annotation_comment",
            title="Delete annotation comment",
            description=_description(
                use="the comment author explicitly wants their comment permanently removed",
                avoid="editing the comment is sufficient",
                result="an impact preview, then a deletion receipt",
                next_step="confirm the exact comment preview before retrying.",
            ),
            input_model=wc.DeleteAnnotationCommentInput,
            output_model=confirmed,
            permission=delete,
            handler=handlers.delete_annotation_comment,
            execution=command,
            destructive=True,
            confirmation=True,
        ),
        _tool(
            name="list_research_outputs",
            title="List research outputs",
            description=_description(
                use="you need stored citations, audio overviews, or data tables",
                avoid="you want to generate a new output or list annotations",
                result="bounded existing outputs in an explicit scope",
                next_step="open one output by immutable item UUID.",
            ),
            input_model=wc.ListResearchOutputsInput,
            output_model=wc.ResearchOutputList,
            permission=read,
            handler=handlers.list_research_outputs,
        ),
        _tool(
            name="get_research_output",
            title="Get research output",
            description=_description(
                use="you know a stored research-output UUID and need its complete content",
                avoid="the UUID identifies an annotation thread or you want generation",
                result="the complete visible stored output",
                next_step="reference its scholens:// URI in durable research notes.",
            ),
            input_model=wc.ResearchOutputInput,
            output_model=ResearchItemResponse,
            permission=read,
            handler=handlers.get_research_output,
        ),
    ]
    shared_names = frozenset(
        definition.name
        for definition in definitions
        if definition.name != "prepare_paper_upload"
    )
    return ToolCatalog(
        definitions=definitions,
        require_agent_metadata=True,
        profiles=[
            ToolProfile(name=CONVERSATION_TOOL_PROFILE, tool_names=shared_names),
            ToolProfile(
                name=MCP_TOOL_PROFILE,
                tool_names=shared_names | {"prepare_paper_upload"},
            ),
        ],
    )


__all__ = [
    "CONVERSATION_TOOL_PROFILE",
    "MCP_TOOL_PROFILE",
    "build_workspace_tool_catalog",
]
