"""Pure rules for reading-activity measurement and privacy."""

from .rules import (
    ACTIVE_READING_DEFINITION_VERSION,
    ANONYMOUS_PROJECT_CONTRIBUTOR_MINIMUM,
    PAGE_VERTICAL_SEGMENT_COUNT,
    PROJECT_READING_ROUNDING_MS,
    SESSION_PAGE_DETAIL_RETENTION_DAYS,
    SESSION_START_BACKLOG_HOURS,
    MAX_READING_SESSION_DURATION_MS,
    MAX_READING_SESSION_HOUR_BUCKETS,
    SNAPSHOT_FUTURE_CLOCK_SKEW_SECONDS,
    SNAPSHOT_VISIBLE_ELAPSED_TOLERANCE_MS,
    SUBSTANTIVE_PAGE_ACTIVE_MS,
    round_project_reading_ms,
)

__all__ = [
    "ACTIVE_READING_DEFINITION_VERSION",
    "ANONYMOUS_PROJECT_CONTRIBUTOR_MINIMUM",
    "PAGE_VERTICAL_SEGMENT_COUNT",
    "PROJECT_READING_ROUNDING_MS",
    "SESSION_PAGE_DETAIL_RETENTION_DAYS",
    "SESSION_START_BACKLOG_HOURS",
    "MAX_READING_SESSION_DURATION_MS",
    "MAX_READING_SESSION_HOUR_BUCKETS",
    "SNAPSHOT_FUTURE_CLOCK_SKEW_SECONDS",
    "SNAPSHOT_VISIBLE_ELAPSED_TOLERANCE_MS",
    "SUBSTANTIVE_PAGE_ACTIVE_MS",
    "round_project_reading_ms",
]
