"""Stable, transport-independent measurement rules."""

from __future__ import annotations

ACTIVE_READING_DEFINITION_VERSION = "active-reading-v1"
PAGE_VERTICAL_SEGMENT_COUNT = 20
SUBSTANTIVE_PAGE_ACTIVE_MS = 15_000
ANONYMOUS_PROJECT_CONTRIBUTOR_MINIMUM = 3
PROJECT_READING_ROUNDING_MS = 5 * 60 * 1_000
SNAPSHOT_VISIBLE_ELAPSED_TOLERANCE_MS = 10_000
SNAPSHOT_FUTURE_CLOCK_SKEW_SECONDS = 5 * 60
SESSION_PAGE_DETAIL_RETENTION_DAYS = 90
SESSION_START_BACKLOG_HOURS = 24
MAX_READING_SESSION_DURATION_MS = 24 * 60 * 60 * 1_000
MAX_READING_SESSION_HOUR_BUCKETS = 26


def round_project_reading_ms(value: int) -> int:
    """Round an aggregate to the nearest privacy-preserving five minutes."""

    if value <= 0:
        return 0
    return int(round(value / PROJECT_READING_ROUNDING_MS)) * (
        PROJECT_READING_ROUNDING_MS
    )


__all__ = [
    "ACTIVE_READING_DEFINITION_VERSION",
    "ANONYMOUS_PROJECT_CONTRIBUTOR_MINIMUM",
    "PAGE_VERTICAL_SEGMENT_COUNT",
    "PROJECT_READING_ROUNDING_MS",
    "SESSION_PAGE_DETAIL_RETENTION_DAYS",
    "SESSION_START_BACKLOG_HOURS",
    "MAX_READING_SESSION_DURATION_MS",
    "MAX_READING_SESSION_HOUR_BUCKETS",
    "SNAPSHOT_FUTURE_CLOCK_SKEW_SECONDS",
    "SNAPSHOT_VISIBLE_ELAPSED_TOLERANCE_MS",
    "SUBSTANTIVE_PAGE_ACTIVE_MS",
    "round_project_reading_ms",
]
