from scholens_job_contracts import (
    ZOTERO_CALLBACK_HEARTBEAT_SECONDS,
    ZOTERO_CALLBACK_HTTP_TIMEOUT_SECONDS,
    ZOTERO_CALLBACK_LEASE_SECONDS,
    ZOTERO_CALLBACK_PROCESSING_TIMEOUT_SECONDS,
)


def test_zotero_callback_timing_contract_has_ordered_safety_margins() -> None:
    assert ZOTERO_CALLBACK_HEARTBEAT_SECONDS < ZOTERO_CALLBACK_LEASE_SECONDS
    assert (
        ZOTERO_CALLBACK_PROCESSING_TIMEOUT_SECONDS
        < ZOTERO_CALLBACK_HTTP_TIMEOUT_SECONDS
        < ZOTERO_CALLBACK_LEASE_SECONDS
    )
