"""Shared, service-neutral background-job contracts."""

from scholens_job_contracts.queues import (
    JOB_QUEUE_NAMES,
    JOBS_WORKER_QUEUE_NAMES,
    JobQueue,
)
from scholens_job_contracts.zotero import (
    MAX_ZOTERO_CALLBACK_BYTES,
    ZOTERO_CALLBACK_HEARTBEAT_SECONDS,
    ZOTERO_CALLBACK_HTTP_TIMEOUT_SECONDS,
    ZOTERO_CALLBACK_LEASE_SECONDS,
    ZOTERO_CALLBACK_PROCESSING_TIMEOUT_SECONDS,
    ZOTERO_SYNC_AUTO_IMPORT_RESERVE_BYTES,
)

__all__ = [
    "JOB_QUEUE_NAMES",
    "JOBS_WORKER_QUEUE_NAMES",
    "JobQueue",
    "MAX_ZOTERO_CALLBACK_BYTES",
    "ZOTERO_CALLBACK_HEARTBEAT_SECONDS",
    "ZOTERO_CALLBACK_HTTP_TIMEOUT_SECONDS",
    "ZOTERO_CALLBACK_LEASE_SECONDS",
    "ZOTERO_CALLBACK_PROCESSING_TIMEOUT_SECONDS",
    "ZOTERO_SYNC_AUTO_IMPORT_RESERVE_BYTES",
]
