"""Service-neutral timing contract for signed Zotero completion callbacks."""

ZOTERO_CALLBACK_HEARTBEAT_SECONDS = 30
ZOTERO_CALLBACK_PROCESSING_TIMEOUT_SECONDS = 12 * 60
ZOTERO_CALLBACK_HTTP_TIMEOUT_SECONDS = 13 * 60
ZOTERO_CALLBACK_LEASE_SECONDS = 15 * 60
