"""scholens initial

Revision ID: b12d7d620e91
Revises:
Create Date: 2026-07-28 10:30:25.961708+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b12d7d620e91"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs_webhook_nonces",
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("nonce"),
        schema="scholens",
    )
    op.create_table(
        "stripe_webhook_events",
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('processing', 'completed', 'failed', 'ignored')",
            name="ck_stripe_webhook_events_status",
        ),
        sa.PrimaryKeyConstraint("event_id"),
        schema="scholens",
    )
    op.create_table(
        "access_keys",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("secret_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=20), nullable=False),
        sa.Column("permissions", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(name) BETWEEN 1 AND 80 AND name = btrim(name)",
            name="ck_access_keys_name",
        ),
        sa.CheckConstraint(
            "secret_hash ~ '^[0-9a-f]{64}$'",
            name="ck_access_keys_secret_hash",
        ),
        sa.CheckConstraint(
            "length(key_prefix) = 20",
            name="ck_access_keys_key_prefix",
        ),
        sa.CheckConstraint(
            "permissions IN ("
            "ARRAY['read']::text[], "
            "ARRAY['write']::text[], "
            "ARRAY['delete']::text[], "
            "ARRAY['read','write']::text[], "
            "ARRAY['read','delete']::text[], "
            "ARRAY['write','delete']::text[], "
            "ARRAY['read','write','delete']::text[]"
            ")",
            name="ck_access_keys_permissions",
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > created_at",
            name="ck_access_keys_expiration",
        ),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoked_at >= created_at",
            name="ck_access_keys_revoked_at",
        ),
        sa.CheckConstraint(
            "last_used_at IS NULL OR last_used_at >= created_at",
            name="ck_access_keys_last_used_at",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "uq_access_keys_secret_hash",
        "access_keys",
        ["secret_hash"],
        unique=True,
        schema="scholens",
    )
    op.execute(
        "CREATE INDEX ix_access_keys_user_created "
        "ON scholens.access_keys (user_id, created_at DESC, id DESC)"
    )
    op.create_index(
        "ix_access_keys_user_revoked",
        "access_keys",
        ["user_id", "revoked_at"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "connector_connections",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("credential_ciphertext", sa.Text(), nullable=False),
        sa.Column(
            "enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('anysearch', 'tavily', 'exa', 'firecrawl')",
            name="ck_connector_connections_provider",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "provider"),
        schema="scholens",
    )
    op.create_table(
        "tool_invocations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("operation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("invocation_key", sa.String(length=512), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("arguments_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default="completed",
            nullable=False,
        ),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["auth.users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "actor_id",
            "invocation_key",
            name="uq_tool_invocations_actor_key",
        ),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_tool_invocations_actor_id"),
        "tool_invocations",
        ["actor_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_tool_invocations_operation_id"),
        "tool_invocations",
        ["operation_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("s3_object_key", sa.String(length=1024), nullable=False),
        sa.Column("preview_s3_key", sa.String(length=1024), nullable=True),
        sa.Column("authors", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("institutions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("keywords", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "summary_citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("publish_date", sa.DateTime(), nullable=True),
        sa.Column("starter_questions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("parser_markdown_s3_key", sa.String(), nullable=True),
        sa.Column("parser_archive_s3_key", sa.String(), nullable=True),
        sa.Column("parser_backend", sa.String(), nullable=True),
        sa.Column("parser_quality", sa.String(), nullable=True),
        sa.Column("parser_version", sa.String(), nullable=True),
        sa.Column("parser_warning_code", sa.String(), nullable=True),
        sa.Column(
            "processing_status",
            sa.String(length=16),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("processing_job_id", sa.UUID(), nullable=True),
        sa.Column("gc_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ts_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column(
            "page_offset_map", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("journal", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("attempted_metadata_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "field_provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parser_backend IS NULL OR parser_backend IN ('mineru', 'pymupdf4llm', 'markitdown')",
            name="ck_documents_parser_backend",
        ),
        sa.CheckConstraint(
            "parser_quality IS NULL OR parser_quality IN ('full', 'text_only')",
            name="ck_documents_parser_quality",
        ),
        sa.CheckConstraint(
            "processing_status IN ('pending', 'processing', 'completed', 'failed')",
            name="ck_documents_processing_status",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", name="uq_documents_sha256"),
        schema="scholens",
    )
    op.create_index(
        "ix_documents_ts_vector",
        "documents",
        ["ts_vector"],
        unique=False,
        schema="scholens",
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_scholens_documents_created_by_id"),
        "documents",
        ["created_by_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_documents_gc_after"),
        "documents",
        ["gc_after"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "onboarding",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("research_fields", sa.String(), nullable=True),
        sa.Column("research_fields_other", sa.String(), nullable=True),
        sa.Column("job_titles", sa.String(), nullable=True),
        sa.Column("job_titles_other", sa.String(), nullable=True),
        sa.Column("reading_frequency", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "paper_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_paper_tags_user_name"),
        schema="scholens",
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["auth.users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_projects_owner_id"),
        "projects",
        ["owner_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("plan", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column("stripe_price_id", sa.String(), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=True),
        sa.Column("stripe_schedule_id", sa.String(), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "token_usage_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("operation_id", sa.String(length=128), nullable=False),
        sa.Column("feature", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("ai_profile", sa.String(length=32), nullable=False),
        sa.Column("thinking", sa.String(length=16), nullable=False),
        sa.Column("thinking_effort", sa.String(length=16), nullable=False),
        sa.Column("profile_revision", sa.String(length=64), nullable=False),
        sa.Column("provider_request_id", sa.String(length=160), nullable=True),
        sa.Column("prompt_tokens", sa.BigInteger(), nullable=False),
        sa.Column("completion_tokens", sa.BigInteger(), nullable=False),
        sa.Column("reasoning_tokens", sa.BigInteger(), nullable=False),
        sa.Column("cache_hit_tokens", sa.BigInteger(), nullable=False),
        sa.Column("cache_miss_tokens", sa.BigInteger(), nullable=False),
        sa.Column("total_tokens", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_token_usage_idempotency_key"),
        schema="scholens",
    )
    op.create_index(
        "ix_token_usage_user_week",
        "token_usage_events",
        ["user_id", "week_start"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "token_weekly_usage",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("used_tokens", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "week_start"),
        schema="scholens",
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("locale", sa.String(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_blocked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "translation_preferences",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "source_language",
            sa.String(length=35),
            server_default="auto",
            nullable=False,
        ),
        sa.Column("target_language", sa.String(length=35), nullable=False),
        sa.Column("custom_instructions", sa.Text(), nullable=True),
        sa.Column(
            "auto_translate_selection",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "full_translation_display",
            sa.String(length=24),
            server_default="bilingual",
            nullable=False,
        ),
        sa.Column(
            "translate_references",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "show_translation_marker",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_language = 'auto' OR "
            "(length(source_language) BETWEEN 2 AND 35 "
            "AND source_language = btrim(source_language))",
            name="ck_translation_preferences_source_language",
        ),
        sa.CheckConstraint(
            "length(target_language) BETWEEN 2 AND 35 "
            "AND target_language = btrim(target_language)",
            name="ck_translation_preferences_language",
        ),
        sa.CheckConstraint(
            "custom_instructions IS NULL "
            "OR (length(custom_instructions) BETWEEN 1 AND 2000 "
            "AND custom_instructions = btrim(custom_instructions))",
            name="ck_translation_preferences_instructions",
        ),
        sa.CheckConstraint(
            "full_translation_display IN ('bilingual', 'translation_only')",
            name="ck_translation_preferences_display",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "translation_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("identity_key", sa.String(length=64), nullable=False),
        sa.Column("context_kind", sa.String(length=24), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("block_id", sa.String(length=128), nullable=True),
        sa.Column("target_language", sa.String(length=35), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("instructions_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_revision", sa.String(length=64), nullable=False),
        sa.Column("profile_revision", sa.String(length=64), nullable=False),
        sa.Column("translated_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "context_kind IN ('selection', 'reflow_block')",
            name="ck_translation_results_context_kind",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_key"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_translation_results_document_id"),
        "translation_results",
        ["document_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "zotero_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("zotero_user_id", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "zotero_oauth_pending",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("origin_operation_id", sa.UUID(), nullable=False),
        sa.Column("oauth_token", sa.String(), nullable=False),
        sa.Column("oauth_token_secret", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_zotero_oauth_pending_oauth_token"),
        "zotero_oauth_pending",
        ["oauth_token"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column(
            "paper_context_kind",
            sa.String(length=16),
            server_default="selection",
            nullable=False,
        ),
        sa.Column(
            "tool_permissions",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{read,write}'::text[]"),
            nullable=False,
        ),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("scope_label_snapshot", sa.String(length=240), nullable=True),
        sa.Column("context_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope_type = 'global' AND project_id IS NULL AND document_id IS NULL AND context_deleted_at IS NULL) OR (scope_type = 'project' AND document_id IS NULL AND ((project_id IS NOT NULL AND context_deleted_at IS NULL) OR (project_id IS NULL AND context_deleted_at IS NOT NULL))) OR (scope_type = 'paper' AND project_id IS NULL AND ((document_id IS NOT NULL AND context_deleted_at IS NULL) OR (document_id IS NULL AND context_deleted_at IS NOT NULL)))",
            name="ck_conversations_scope_consistency",
        ),
        sa.CheckConstraint(
            "paper_context_kind IN ('library', 'selection')",
            name="ck_conversations_paper_context_kind",
        ),
        sa.CheckConstraint(
            "tool_permissions IN ("
            "ARRAY[]::text[], "
            "ARRAY['read']::text[], "
            "ARRAY['write']::text[], "
            "ARRAY['delete']::text[], "
            "ARRAY['read','write']::text[], "
            "ARRAY['read','delete']::text[], "
            "ARRAY['write','delete']::text[], "
            "ARRAY['read','write','delete']::text[]"
            ")",
            name="ck_conversations_tool_permissions",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_conversations_user_archive_activity",
        "conversations",
        ["user_id", "archived_at", "updated_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_conversations_user_pinned",
        "conversations",
        ["user_id", "pinned_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_conversations_document_id"),
        "conversations",
        ["document_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_conversations_project_id"),
        "conversations",
        ["project_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "conversation_context_projects",
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["scholens.conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("conversation_id", "project_id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_conversation_context_projects_project_id"),
        "conversation_context_projects",
        ["project_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "conversation_context_documents",
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["scholens.conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("conversation_id", "document_id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_conversation_context_documents_document_id"),
        "conversation_context_documents",
        ["document_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("operation", sa.String(length=40), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("origin_operation_id", sa.UUID(), nullable=False),
        sa.Column("requested_by_id", sa.BigInteger(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default="pending", nullable=False
        ),
        sa.Column("progress_code", sa.String(length=40), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed', 'cancelled')",
            name="ck_jobs_status",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_jobs_idempotency_key"),
        schema="scholens",
    )
    op.create_index(
        "ix_jobs_document_status",
        "jobs",
        ["document_id", "status"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_jobs_correlation_id"),
        "jobs",
        ["correlation_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_jobs_origin_operation_id"),
        "jobs",
        ["origin_operation_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_jobs_project_status",
        "jobs",
        ["project_id", "status"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_jobs_requester_activity",
        "jobs",
        ["requested_by_id", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "document_reflows",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("pipeline_revision", sa.String(length=64), nullable=True),
        sa.Column("parser_revision", sa.String(length=64), nullable=True),
        sa.Column(
            "warnings",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'failed')",
            name="ck_document_reflows_status",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["scholens.jobs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("document_id"),
        sa.UniqueConstraint("job_id"),
        schema="scholens",
    )
    op.create_table(
        "document_reflow_assets",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column(
            "source_rect",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('raster', 'vector', 'composite', 'table_preview')",
            name="ck_reflow_assets_kind",
        ),
        sa.CheckConstraint("width > 0 AND height > 0", name="ck_reflow_assets_size"),
        sa.CheckConstraint("page_number > 0", name="ck_reflow_assets_page"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["scholens.document_reflows.document_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
        schema="scholens",
    )
    op.create_index(
        "ix_document_reflow_assets_document",
        "document_reflow_assets",
        ["document_id", "page_number"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "document_reflow_blocks",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("block_index", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("render_markdown", sa.Text(), nullable=False),
        sa.Column("group_id", sa.String(length=128), nullable=True),
        sa.Column("heading_level", sa.Integer(), nullable=True),
        sa.Column(
            "source_spans",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("presentation_status", sa.String(length=16), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("block_index >= 0", name="ck_reflow_blocks_index"),
        sa.CheckConstraint(
            "kind IN ('eyebrow', 'title', 'authors', 'affiliations', 'abstract', "
            "'keywords', 'heading', 'paragraph', 'list', 'quote', 'equation', "
            "'table', 'figure', 'caption', 'code', 'footnote', 'references')",
            name="ck_reflow_blocks_kind",
        ),
        sa.CheckConstraint(
            "presentation_status IN ('verbatim', 'repaired', 'degraded')",
            name="ck_reflow_blocks_presentation_status",
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["scholens.document_reflow_assets.id"],
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "heading_level IS NULL OR heading_level BETWEEN 1 AND 6",
            name="ck_reflow_blocks_heading_level",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["scholens.document_reflows.document_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id",
            "block_index",
            name="uq_document_reflow_blocks_document_index",
        ),
        schema="scholens",
    )
    op.create_index(
        "ix_document_reflow_blocks_document",
        "document_reflow_blocks",
        ["document_id", "block_index"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "library_papers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), server_default="reading", nullable=False),
        sa.Column(
            "last_accessed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_public", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("share_token_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "metadata_overrides",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "document_id", name="uq_library_papers_user_document"
        ),
        schema="scholens",
    )
    op.create_index(
        "ix_library_papers_user_activity",
        "library_papers",
        ["user_id", "updated_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_library_papers_document_id"),
        "library_papers",
        ["document_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_library_papers_share_token_hash"),
        "library_papers",
        ["share_token_hash"],
        unique=True,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_library_papers_user_id"),
        "library_papers",
        ["user_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "document_passages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("ts_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "start_line"),
        schema="scholens",
    )
    op.create_index(
        "ix_document_passages_ts_vector",
        "document_passages",
        ["ts_vector"],
        unique=False,
        schema="scholens",
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_scholens_document_passages_document_id"),
        "document_passages",
        ["document_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "project_collaborators",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "can_edit_project", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "can_manage_papers", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "can_manage_collaborators",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "user_id", name="uq_project_collaborator_project_user"
        ),
        schema="scholens",
    )
    op.create_index(
        "ix_project_collaborators_user_id",
        "project_collaborators",
        ["user_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "project_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "can_edit_project", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "can_manage_papers", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "can_manage_collaborators",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"], ["auth.users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_project_invitations_project_email",
        "project_invitations",
        ["project_id", "email"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_project_invitations_token_hash",
        "project_invitations",
        ["token_hash"],
        unique=True,
        schema="scholens",
    )
    op.create_index(
        "uq_project_invitations_pending_project_email",
        "project_invitations",
        ["project_id", "email"],
        unique=True,
        schema="scholens",
        postgresql_where=sa.text("accepted_at IS NULL AND revoked_at IS NULL"),
    )
    op.create_table(
        "project_papers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("added_by_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["added_by_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "document_id", name="uq_project_papers_project_document"
        ),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_project_papers_document_id"),
        "project_papers",
        ["document_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_project_papers_project_id"),
        "project_papers",
        ["project_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "job_dispatches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("task_name", sa.String(length=120), nullable=False),
        sa.Column("queue", sa.String(length=80), nullable=False),
        sa.Column("kwargs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default="pending", nullable=False
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("last_error_detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'publishing', 'published')",
            name="ck_job_dispatches_status",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["scholens.jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
        schema="scholens",
    )
    op.create_index(
        "ix_job_dispatches_pending",
        "job_dispatches",
        ["status", "available_at", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "library_paper_tags",
        sa.Column("library_paper_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["library_paper_id"], ["scholens.library_papers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["scholens.paper_tags.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("library_paper_id", "tag_id"),
        schema="scholens",
    )
    op.create_table(
        "conversation_turns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("created_operation_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("user_query", sa.Text(), nullable=False),
        sa.Column("contexts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "suggestions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reasoning_level", sa.String(length=16), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("time_zone", sa.String(length=100), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("selected_response_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["scholens.conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id",
            "sequence",
            name="uq_conversation_turns_conversation_sequence",
        ),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_conversation_turns_created_operation_id"),
        "conversation_turns",
        ["created_operation_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_conversation_turns_correlation_id"),
        "conversation_turns",
        ["correlation_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "conversation_responses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("turn_id", sa.UUID(), nullable=False),
        sa.Column("created_operation_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("variant_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trace", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed', 'cancelled')",
            name="ck_conversation_responses_status",
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["scholens.conversation_turns.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "turn_id", "variant_index", name="uq_conversation_responses_turn_variant"
        ),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_conversation_responses_turn_id"),
        "conversation_responses",
        ["turn_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_conversation_responses_created_operation_id"),
        "conversation_responses",
        ["created_operation_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_conversation_responses_correlation_id"),
        "conversation_responses",
        ["correlation_id"],
        unique=False,
        schema="scholens",
    )
    op.create_foreign_key(
        "fk_conversation_turns_selected_response_id",
        "conversation_turns",
        "conversation_responses",
        ["selected_response_id"],
        ["id"],
        source_schema="scholens",
        referent_schema="scholens",
        ondelete="SET NULL",
    )
    op.create_table(
        "operation_journal_entries",
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("causation_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("initiated_by", sa.String(length=16), nullable=False),
        sa.Column("origin_kind", sa.String(length=32), nullable=False),
        sa.Column("origin_name", sa.String(length=128), nullable=True),
        sa.Column("origin_reference", sa.String(length=64), nullable=True),
        sa.Column("credential_kind", sa.String(length=32), nullable=True),
        sa.Column("credential_id", sa.String(length=128), nullable=True),
        sa.Column("request_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("turn_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=127), nullable=False),
        sa.Column("resources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "initiated_by IN ('user', 'agent', 'system')",
            name="ck_operation_journal_initiator",
        ),
        sa.CheckConstraint(
            "origin_kind IN ("
            "'http', 'conversation', 'mcp', 'job', 'webhook', "
            "'oauth_callback', 'scheduler'"
            ")",
            name="ck_operation_journal_origin",
        ),
        sa.CheckConstraint(
            "credential_kind IS NULL OR credential_kind IN ("
            "'cloud_session', 'access_key', 'internal_signature', "
            "'provider_signature'"
            ")",
            name="ck_operation_journal_credential",
        ),
        sa.CheckConstraint(
            "action ~ '^[a-z][a-z0-9_]{0,62}\\.[a-z][a-z0-9_]{0,62}$'",
            name="ck_operation_journal_action",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(resources) = 'array' "
            "AND jsonb_array_length(resources) BETWEEN 1 AND 100",
            name="ck_operation_journal_resources",
        ),
        sa.CheckConstraint(
            "(causation_id IS NULL AND operation_id = correlation_id) OR "
            "(causation_id IS NOT NULL "
            "AND operation_id <> correlation_id "
            "AND operation_id <> causation_id)",
            name="ck_operation_journal_trace",
        ),
        sa.CheckConstraint(
            "created_at = updated_at",
            name="ck_operation_journal_append_only_timestamp",
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["auth.users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("entry_id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_operation_journal_entries_actor_id"),
        "operation_journal_entries",
        ["actor_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_operation_journal_entries_correlation_id"),
        "operation_journal_entries",
        ["correlation_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_operation_journal_entries_operation_id"),
        "operation_journal_entries",
        ["operation_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "upload_reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quota_owner_id", sa.BigInteger(), nullable=False),
        sa.Column("reserved_size_kb", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "reserved_reference_count", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "reference_created", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("original_filename", sa.String(length=512), nullable=True),
        sa.Column("display_name", sa.String(length=512), nullable=False),
        sa.Column("source_kind", sa.String(length=16), nullable=False),
        sa.Column("superseded_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reserved_reference_count IN (0, 1)",
            name="ck_upload_reservations_reserved_reference_count",
        ),
        sa.CheckConstraint(
            "reserved_size_kb >= 0",
            name="ck_upload_reservations_reserved_size_nonnegative",
        ),
        sa.ForeignKeyConstraint(["id"], ["scholens.jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["scholens.upload_reservations.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quota_owner_id"], ["auth.users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_upload_reservations_content_sha256"),
        "upload_reservations",
        ["content_sha256"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_upload_reservations_quota_owner",
        "upload_reservations",
        ["quota_owner_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_upload_reservations_superseded_by",
        "upload_reservations",
        ["superseded_by_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "research_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("audience_type", sa.String(length=16), nullable=False),
        sa.Column("audience_document_id", sa.UUID(), nullable=True),
        sa.Column("audience_project_id", sa.UUID(), nullable=True),
        sa.Column("target_document_id", sa.UUID(), nullable=True),
        sa.Column("source_response_id", sa.UUID(), nullable=True),
        sa.Column("source_job_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(audience_type = 'personal' AND audience_document_id IS NULL AND audience_project_id IS NULL) OR (audience_type = 'document' AND audience_document_id IS NOT NULL AND audience_project_id IS NULL) OR (audience_type = 'project' AND audience_project_id IS NOT NULL AND audience_document_id IS NULL)",
            name="ck_research_items_audience_consistency",
        ),
        sa.CheckConstraint(
            "kind != 'annotation_thread' OR (target_document_id IS NOT NULL AND audience_type IN ('personal', 'project'))",
            name="ck_research_items_annotation_audience",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["audience_document_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["audience_project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_document_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_job_id"], ["scholens.jobs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_response_id"],
            ["scholens.conversation_responses.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_job_id"),
        schema="scholens",
    )
    op.create_index(
        "ix_research_items_creator_activity",
        "research_items",
        ["created_by_id", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_research_items_document_audience",
        "research_items",
        ["audience_document_id", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_research_items_project_audience",
        "research_items",
        ["audience_project_id", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_research_items_annotation_target",
        "research_items",
        ["target_document_id", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "zotero_imported_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("zotero_item_key", sa.String(), nullable=False),
        sa.Column("zotero_attachment_key", sa.String(), nullable=True),
        sa.Column("import_source", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("upload_job_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "annotations_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["upload_job_id"], ["scholens.upload_reservations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "zotero_item_key", name="uq_zotero_import_user_item"
        ),
        schema="scholens",
    )
    op.create_table(
        "citation_outputs",
        sa.Column("research_item_id", sa.UUID(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["research_item_id"], ["scholens.research_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("research_item_id"),
        schema="scholens",
    )
    op.create_table(
        "annotation_threads",
        sa.Column("research_item_id", sa.UUID(), nullable=False),
        sa.Column("quote_text", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("position", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "color", sa.String(length=32), server_default="yellow", nullable=False
        ),
        sa.Column("role", sa.String(length=16), server_default="user", nullable=False),
        sa.Column("zotero_annotation_key", sa.String(length=255), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default="open", nullable=False
        ),
        sa.Column("resolved_by_id", sa.BigInteger(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "color IN ('yellow', 'red', 'green', 'blue', 'purple', 'magenta', 'orange', 'gray')",
            name="ck_annotation_threads_color",
        ),
        sa.CheckConstraint(
            "status IN ('open', 'resolved')",
            name="ck_annotation_threads_status",
        ),
        sa.CheckConstraint(
            "(status = 'open' AND resolved_by_id IS NULL AND resolved_at IS NULL) OR (status = 'resolved' AND resolved_at IS NOT NULL)",
            name="ck_annotation_threads_resolution",
        ),
        sa.ForeignKeyConstraint(
            ["research_item_id"], ["scholens.research_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("research_item_id"),
        schema="scholens",
    )
    op.create_table(
        "research_audio_overviews",
        sa.Column("research_item_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("s3_object_key", sa.String(length=1024), nullable=False),
        sa.Column("voice_id", sa.String(length=160), nullable=False),
        sa.Column("model_version", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["research_item_id"], ["scholens.research_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("research_item_id"),
        schema="scholens",
    )
    op.create_table(
        "research_data_tables",
        sa.Column("research_item_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=True),
        sa.Column("columns", sa.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "rows",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "row_failures",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["research_item_id"], ["scholens.research_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("research_item_id"),
        schema="scholens",
    )
    op.create_table(
        "annotation_comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=16), server_default="user", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["scholens.annotation_threads.research_item_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_annotation_comments_thread",
        "annotation_comments",
        ["thread_id", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.execute(
        """
        CREATE FUNCTION scholens.document_content_trigger() RETURNS trigger AS $$
        BEGIN
            NEW.ts_vector :=
                setweight(
                    to_tsvector('pg_catalog.english', coalesce(NEW.title, '')),
                    'A'
                ) ||
                setweight(
                    to_tsvector(
                        'pg_catalog.english',
                        coalesce(array_to_string(NEW.authors, ' '), '')
                    ),
                    'A'
                ) ||
                setweight(
                    to_tsvector(
                        'pg_catalog.english',
                        coalesce(array_to_string(NEW.keywords, ' '), '')
                    ),
                    'B'
                ) ||
                setweight(
                    to_tsvector('pg_catalog.english', coalesce(NEW.abstract, '')),
                    'C'
                ) ||
                setweight(
                    to_tsvector('pg_catalog.english', coalesce(NEW.raw_content, '')),
                    'D'
                );
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER tsvectorupdate
            BEFORE INSERT OR UPDATE ON scholens.documents
            FOR EACH ROW
            EXECUTE FUNCTION scholens.document_content_trigger()
        """
    )
    op.execute(
        """
        CREATE FUNCTION scholens.document_passages_tsvector_trigger()
        RETURNS trigger AS $$
        BEGIN
            NEW.ts_vector :=
                to_tsvector('pg_catalog.english', coalesce(NEW.content, ''));
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER document_passages_tsvectorupdate
            BEFORE INSERT OR UPDATE ON scholens.document_passages
            FOR EACH ROW
            EXECUTE FUNCTION scholens.document_passages_tsvector_trigger()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER IF EXISTS document_passages_tsvectorupdate "
        "ON scholens.document_passages"
    )
    op.execute("DROP FUNCTION IF EXISTS scholens.document_passages_tsvector_trigger()")
    op.execute("DROP TRIGGER IF EXISTS tsvectorupdate ON scholens.documents")
    op.execute("DROP FUNCTION IF EXISTS scholens.document_content_trigger()")
    op.drop_index(
        "ix_annotation_comments_thread",
        table_name="annotation_comments",
        schema="scholens",
    )
    op.drop_table("annotation_comments", schema="scholens")
    op.drop_table("research_data_tables", schema="scholens")
    op.drop_table("research_audio_overviews", schema="scholens")
    op.drop_table("annotation_threads", schema="scholens")
    op.drop_table("citation_outputs", schema="scholens")
    op.drop_table("zotero_imported_items", schema="scholens")
    op.drop_index(
        "ix_research_items_annotation_target",
        table_name="research_items",
        schema="scholens",
    )
    op.drop_index(
        "ix_research_items_project_audience",
        table_name="research_items",
        schema="scholens",
    )
    op.drop_index(
        "ix_research_items_document_audience",
        table_name="research_items",
        schema="scholens",
    )
    op.drop_index(
        "ix_research_items_creator_activity",
        table_name="research_items",
        schema="scholens",
    )
    op.drop_table("research_items", schema="scholens")
    op.drop_index(
        "ix_upload_reservations_superseded_by",
        table_name="upload_reservations",
        schema="scholens",
    )
    op.drop_index(
        "ix_upload_reservations_quota_owner",
        table_name="upload_reservations",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_upload_reservations_content_sha256"),
        table_name="upload_reservations",
        schema="scholens",
    )
    op.drop_table("upload_reservations", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_operation_journal_entries_operation_id"),
        table_name="operation_journal_entries",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_operation_journal_entries_correlation_id"),
        table_name="operation_journal_entries",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_operation_journal_entries_actor_id"),
        table_name="operation_journal_entries",
        schema="scholens",
    )
    op.drop_table("operation_journal_entries", schema="scholens")
    op.drop_constraint(
        "fk_conversation_turns_selected_response_id",
        "conversation_turns",
        schema="scholens",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_scholens_conversation_responses_correlation_id"),
        table_name="conversation_responses",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_conversation_responses_created_operation_id"),
        table_name="conversation_responses",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_conversation_responses_turn_id"),
        table_name="conversation_responses",
        schema="scholens",
    )
    op.drop_table("conversation_responses", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_conversation_turns_correlation_id"),
        table_name="conversation_turns",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_conversation_turns_created_operation_id"),
        table_name="conversation_turns",
        schema="scholens",
    )
    op.drop_table("conversation_turns", schema="scholens")
    op.drop_table("library_paper_tags", schema="scholens")
    op.drop_index(
        "ix_job_dispatches_pending", table_name="job_dispatches", schema="scholens"
    )
    op.drop_table("job_dispatches", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_project_papers_project_id"),
        table_name="project_papers",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_project_papers_document_id"),
        table_name="project_papers",
        schema="scholens",
    )
    op.drop_table("project_papers", schema="scholens")
    op.drop_index(
        "uq_project_invitations_pending_project_email",
        table_name="project_invitations",
        schema="scholens",
        postgresql_where=sa.text("accepted_at IS NULL AND revoked_at IS NULL"),
    )
    op.drop_index(
        "ix_project_invitations_token_hash",
        table_name="project_invitations",
        schema="scholens",
    )
    op.drop_index(
        "ix_project_invitations_project_email",
        table_name="project_invitations",
        schema="scholens",
    )
    op.drop_table("project_invitations", schema="scholens")
    op.drop_index(
        "ix_project_collaborators_user_id",
        table_name="project_collaborators",
        schema="scholens",
    )
    op.drop_table("project_collaborators", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_document_passages_document_id"),
        table_name="document_passages",
        schema="scholens",
    )
    op.drop_index(
        "ix_document_passages_ts_vector",
        table_name="document_passages",
        schema="scholens",
        postgresql_using="gin",
    )
    op.drop_table("document_passages", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_library_papers_user_id"),
        table_name="library_papers",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_library_papers_share_token_hash"),
        table_name="library_papers",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_library_papers_document_id"),
        table_name="library_papers",
        schema="scholens",
    )
    op.drop_index(
        "ix_library_papers_user_activity",
        table_name="library_papers",
        schema="scholens",
    )
    op.drop_table("library_papers", schema="scholens")
    op.drop_index(
        "ix_document_reflow_blocks_document",
        table_name="document_reflow_blocks",
        schema="scholens",
    )
    op.drop_table("document_reflow_blocks", schema="scholens")
    op.drop_index(
        "ix_document_reflow_assets_document",
        table_name="document_reflow_assets",
        schema="scholens",
    )
    op.drop_table("document_reflow_assets", schema="scholens")
    op.drop_table("document_reflows", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_jobs_origin_operation_id"),
        table_name="jobs",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_jobs_correlation_id"),
        table_name="jobs",
        schema="scholens",
    )
    op.drop_index("ix_jobs_requester_activity", table_name="jobs", schema="scholens")
    op.drop_index("ix_jobs_project_status", table_name="jobs", schema="scholens")
    op.drop_index("ix_jobs_document_status", table_name="jobs", schema="scholens")
    op.drop_table("jobs", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_conversation_context_documents_document_id"),
        table_name="conversation_context_documents",
        schema="scholens",
    )
    op.drop_table("conversation_context_documents", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_conversation_context_projects_project_id"),
        table_name="conversation_context_projects",
        schema="scholens",
    )
    op.drop_table("conversation_context_projects", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_conversations_project_id"),
        table_name="conversations",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_conversations_document_id"),
        table_name="conversations",
        schema="scholens",
    )
    op.drop_index(
        "ix_conversations_user_pinned", table_name="conversations", schema="scholens"
    )
    op.drop_index(
        "ix_conversations_user_archive_activity",
        table_name="conversations",
        schema="scholens",
    )
    op.drop_table("conversations", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_zotero_oauth_pending_oauth_token"),
        table_name="zotero_oauth_pending",
        schema="scholens",
    )
    op.drop_table("zotero_oauth_pending", schema="scholens")
    op.drop_table("zotero_connections", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_translation_results_document_id"),
        table_name="translation_results",
        schema="scholens",
    )
    op.drop_table("translation_results", schema="scholens")
    op.drop_table("translation_preferences", schema="scholens")
    op.drop_table("user_profiles", schema="scholens")
    op.drop_table("token_weekly_usage", schema="scholens")
    op.drop_index(
        "ix_token_usage_user_week", table_name="token_usage_events", schema="scholens"
    )
    op.drop_table("token_usage_events", schema="scholens")
    op.drop_table("subscriptions", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_projects_owner_id"), table_name="projects", schema="scholens"
    )
    op.drop_table("projects", schema="scholens")
    op.drop_table("paper_tags", schema="scholens")
    op.drop_table("onboarding", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_documents_gc_after"),
        table_name="documents",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_documents_created_by_id"),
        table_name="documents",
        schema="scholens",
    )
    op.drop_index(
        "ix_documents_ts_vector",
        table_name="documents",
        schema="scholens",
        postgresql_using="gin",
    )
    op.drop_table("documents", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_tool_invocations_operation_id"),
        table_name="tool_invocations",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_tool_invocations_actor_id"),
        table_name="tool_invocations",
        schema="scholens",
    )
    op.drop_table("tool_invocations", schema="scholens")
    op.drop_table("connector_connections", schema="scholens")
    op.drop_index(
        "ix_access_keys_user_revoked",
        table_name="access_keys",
        schema="scholens",
    )
    op.drop_index(
        "ix_access_keys_user_created",
        table_name="access_keys",
        schema="scholens",
    )
    op.drop_index(
        "uq_access_keys_secret_hash",
        table_name="access_keys",
        schema="scholens",
    )
    op.drop_table("access_keys", schema="scholens")
    op.drop_table("stripe_webhook_events", schema="scholens")
    op.drop_table("jobs_webhook_nonces", schema="scholens")
    # ### end Alembic commands ###
