export const semanticIcons = {
  AddAnnotationIcon: "Notes",
  AccountIcon: "User",
  AddIcon: "Plus",
  AppearanceIcon: "SettingsProfiles",
  AskIcon: "ChatBubbleQuestion",
  AudioIcon: "Headset",
  BackIcon: "ArrowLeft",
  CitationIcon: "Journal",
  ClosePanelIcon: "SidebarCollapse",
  CollapseRailIcon: "FastArrowLeft",
  ConfirmIcon: "Check",
  CommentIcon: "ChatBubble",
  CopyIcon: "Copy",
  DataTableIcon: "TableRows",
  IntegrationIcon: "Network",
  KeyIcon: "Key",
  DeleteIcon: "Trash",
  DismissIcon: "Xmark",
  DocumentIcon: "Page",
  DownloadIcon: "Download",
  EditIcon: "EditPencil",
  EmailIcon: "Mail",
  ErrorIcon: "WarningCircle",
  ExpandIcon: "NavArrowDown",
  ExpandRailIcon: "FastArrowRight",
  FilterIcon: "FilterList",
  FitIcon: "Frame",
  HighlightColorIcon: "ColorPicker",
  IncompleteIcon: "Circle",
  InsightIcon: "LightBulb",
  LanguageIcon: "Language",
  LibraryIcon: "Book",
  LinkIcon: "Link",
  MentionIcon: "AtSign",
  MenuIcon: "Menu",
  MoreIcon: "MoreHoriz",
  NewConversationIcon: "Edit",
  NextIcon: "NavArrowRight",
  OpenPanelIcon: "SidebarExpand",
  OutlineIcon: "List",
  PinIcon: "Pin",
  PreviousIcon: "NavArrowLeft",
  ProjectIcon: "Folder",
  QuoteIcon: "Quote",
  RegenerateIcon: "Refresh",
  ReopenIcon: "Undo",
  RetryIcon: "RefreshDouble",
  SearchIcon: "Search",
  SendIcon: "ArrowUp",
  SettingsIcon: "Settings",
  SignOutIcon: "LogOut",
  StopIcon: "Square",
  SuccessIcon: "CheckCircle",
  TagIcon: "Label",
  TranslationIcon: "Translate",
  UsageIcon: "GraphUp",
  UploadIcon: "Upload",
  WarningIcon: "WarningTriangle",
  WorkspaceActionIcon: "TaskList",
  ZoomInIcon: "ZoomIn",
  ZoomOutIcon: "ZoomOut",
} as const;

export {
  Notes as AddAnnotationIcon,
  User as AccountIcon,
  Plus as AddIcon,
  SettingsProfiles as AppearanceIcon,
  ChatBubbleQuestion as AskIcon,
  Headset as AudioIcon,
  ArrowLeft as BackIcon,
  Journal as CitationIcon,
  SidebarCollapse as ClosePanelIcon,
  FastArrowLeft as CollapseRailIcon,
  Check as ConfirmIcon,
  ChatBubble as CommentIcon,
  Copy as CopyIcon,
  TableRows as DataTableIcon,
  Network as IntegrationIcon,
  Key as KeyIcon,
  Trash as DeleteIcon,
  Xmark as DismissIcon,
  Page as DocumentIcon,
  Download as DownloadIcon,
  EditPencil as EditIcon,
  Mail as EmailIcon,
  WarningCircle as ErrorIcon,
  NavArrowDown as ExpandIcon,
  FastArrowRight as ExpandRailIcon,
  FilterList as FilterIcon,
  Frame as FitIcon,
  ColorPicker as HighlightColorIcon,
  Circle as IncompleteIcon,
  LightBulb as InsightIcon,
  Language as LanguageIcon,
  Book as LibraryIcon,
  Link as LinkIcon,
  AtSign as MentionIcon,
  Menu as MenuIcon,
  MoreHoriz as MoreIcon,
  Edit as NewConversationIcon,
  NavArrowRight as NextIcon,
  SidebarExpand as OpenPanelIcon,
  List as OutlineIcon,
  Pin as PinIcon,
  NavArrowLeft as PreviousIcon,
  Folder as ProjectIcon,
  Quote as QuoteIcon,
  Refresh as RegenerateIcon,
  Undo as ReopenIcon,
  RefreshDouble as RetryIcon,
  Search as SearchIcon,
  ArrowUp as SendIcon,
  Settings as SettingsIcon,
  LogOut as SignOutIcon,
  Square as StopIcon,
  CheckCircle as SuccessIcon,
  Label as TagIcon,
  Translate as TranslationIcon,
  GraphUp as UsageIcon,
  Upload as UploadIcon,
  WarningTriangle as WarningIcon,
  TaskList as WorkspaceActionIcon,
  ZoomIn as ZoomInIcon,
  ZoomOut as ZoomOutIcon,
} from "iconoir-react";
