"""Retained-size policy shared by bounded personal-Library producers."""

LIBRARY_PAPER_LIST_MAX_PAGE_ITEMS = 5
LIBRARY_PAPER_LONG_TEXT_JSON_BYTES = 512
LIBRARY_PAPER_TEXT_JSON_BYTES = 256
LIBRARY_PAPER_LIST_VALUE_JSON_BYTES = 128
LIBRARY_PAPER_KEYWORD_JSON_BYTES = 96
LIBRARY_PAPER_MAX_AUTHORS = 6
LIBRARY_PAPER_MAX_INSTITUTIONS = 4
LIBRARY_PAPER_MAX_KEYWORDS = 8
LIBRARY_PAPER_MAX_TAGS = 8
LIBRARY_PAPER_MAX_CITATIONS = 4
LIBRARY_PAPER_MAX_STARTER_QUESTIONS = 4

__all__ = [
    "LIBRARY_PAPER_KEYWORD_JSON_BYTES",
    "LIBRARY_PAPER_LIST_MAX_PAGE_ITEMS",
    "LIBRARY_PAPER_LIST_VALUE_JSON_BYTES",
    "LIBRARY_PAPER_LONG_TEXT_JSON_BYTES",
    "LIBRARY_PAPER_MAX_AUTHORS",
    "LIBRARY_PAPER_MAX_CITATIONS",
    "LIBRARY_PAPER_MAX_INSTITUTIONS",
    "LIBRARY_PAPER_MAX_KEYWORDS",
    "LIBRARY_PAPER_MAX_STARTER_QUESTIONS",
    "LIBRARY_PAPER_MAX_TAGS",
    "LIBRARY_PAPER_TEXT_JSON_BYTES",
]
