bind 0.0.0.0
port 0
tls-port 6380
tls-cert-file /run/valkey-tls/server.crt
tls-key-file /run/valkey-tls/server.key
tls-ca-cert-file /run/trust/private-ca.pem
tls-auth-clients no
protected-mode yes
dir /data
appendonly yes
appendfsync everysec
maxmemory 192mb
maxmemory-policy noeviction
save 900 1
loglevel warning
